version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db  # frontendはここでは不要
    environment:
      DB_HOST: db  # データベースホストとしてコンテナ名「db」を指定
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: dedede_db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # node_modulesをローカルと分離
    stdin_open: true
    tty: true

  db:
    image: postgres:14  # PostgreSQLのイメージを指定
    platform: linux/amd64
    environment:
      POSTGRES_USER: user  # ユーザー名
      POSTGRES_PASSWORD: password  # ユーザーパスワード
      POSTGRES_DB: dedede_db  # 初期データベース名
    volumes:
      - db_data:/var/lib/postgresql/data  # PostgreSQLデータの永続化
    ports:
      - "5432:5432"  # PostgreSQLのポートをマッピング

volumes:
  db_data: