version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # node_modulesをローカルと分離
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7  # MySQLのイメージを指定
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # rootパスワード
      MYSQL_DATABASE: dedede_db  # 初期データベース名
      MYSQL_USER: user  # ユーザー名
      MYSQL_PASSWORD: password  # ユーザーパスワード
    volumes:
      - db_data:/var/lib/mysql  # MySQLデータの永続化
    ports:
      - "3306:3306"  # MySQLのポートをマッピング

volumes:
  db_data: